locale: en-US
title: "Zhou Xuan's Homepage"
name: "Zhou Xuan"
description: "Ph.D. Student at NAIST"
url: "https://xuanzhou111.github.io"
baseurl: ""
repository: "xuanZhou111/xuanZhou111.github.io"
timezone: Asia/Tokyo
theme: null

author:
  avatar: "profile.png"
  name: "Zhou Xuan | 周璇"
  bio: "Ph.D. Student (D2) @ NAIST <br> Natural Language Processing Lab"
  location: "Osaka, Japan"
  email: "xuan.zhou.xc7@naist.ac.jp"
  googlescholar: "https://scholar.google.com/citations?user=V5Z7HzMAAAAJ&hl=en"
  github: "xuanZhou111"

include:
  - _pages

exclude:
  - .asset-cache
  - .bundle
  - .devcontainer
  - .github
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README*
  - vendor

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
